### ISSUE TITLE
Team columns

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-db#11]
What information would we want to see in a team's database?

- name
- last submission URL
- last submission time
- last submission build log
- last successful submission URL
- last successful submission time
- last successful submission build log
- is eligible for prizes

If we use team-logins rather than user-logins
- email
- password

**Comment by renodubois** [comment]
This looks good to me

**Comment by renodubois** [comment]
So some proposed changes moving along with the team-only system would look like:

- Having some info about that team (i.e. `name`, `password`)
- Having a "main contact" name and email for email verification purposes and any sort of contact needs (we can expand this to have additional contact info if needed)

Using this model we would really only need the team & game table (unless I'm majorly overlooking something).

Would love to hear some feedback regarding these changes.

**Comment by user404d** [comment]
Teams have a main contact, password, and name.
