### ISSUE TITLE
User columns

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-db#12]
Do we even need this?

I personally prefer the idea of having a single team login. 
It reduces the need for a user table and a team-member table.

There isnt much information we would gain from individual users.
The only thing this would add is pre-payment, but it seems there might be an easier way to do this without relying on this database of users.

**Comment by renodubois** [comment]
At least for now, I think a single team login is fine. It makes our lives a bit easier in developing

**Comment by user404d** [comment]
Settled on teams only.
