### ISSUE TITLE
Add Submissions Table

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-db#14]
story: #18 

- [x] Globally auto-incrementing ID - Not Null
- [x] Foreign Team ID (number) - Not Null
- [x] Version (number) - Not Null
- [x] Status: queueing, building, finished, failed; defaults to queueing
- [x] Output URL (string)
- [x] Submission URL (string)
- [x] Docker Image (string)

**Comment by user404d** [comment]
Submission is now added for a team.
