### ISSUE TITLE
Add verification/testing to init.sql schema

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-db#4]
We need a general purpose way to verify our SQL schema is actually valid in a PostgreSQL environment. 

Ideally, a script is developed to test this that works locally and in a Travis CI environment

**Comment by russleyshaw** [comment]
### Ideas
- Create a blank Postgresql docker container and run the init.sql directly against database.

**Comment by user404d** [comment]
Created `test.sh` and `test.local.sh` to get direct feedback from execution of `init.sql`.
